CREATE TABLE game_details_batter (
	game_id INTEGER,
	game_date DATE,
	team_id TEXT,
	batter_id INTEGER,
	batter_name TEXT,
	at_bat INTEGER,
	single INTEGER,
	double INTEGER,
	triple INTEGER,
	home_run INTEGER,
	walk INTEGER,
	intent_walk INTEGER,
	hit_by_pitch INTEGER,
	strikeout INTEGER,
	field_out INTEGER,
	double_play INTEGER,
	field_choice INTEGER,
	field_choice_out INTEGER,
	force_out INTEGER,
	triple_play INTEGER,
	reach_by_error INTEGER,
	sac_fly INTEGER,
	sac_bunt INTEGER,
	stolen_base INTEGER,
	caught_stealing INTEGER,
	pickoff_caught INTEGER,
	other INTEGER,
	ejection INTEGER,
	season INTEGER,
	PRIMARY KEY (batter_id, game_id)
)